<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-GLAJOS1C" failures="1" tests="3" name="Test" time="51.556" errors="0" timestamp="2025-10-25T15:12:12 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="39.861"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="8.489">
    <failure type="java.lang.AssertionError" message="expected [7] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [7] but found [5]
at stepDefinitions.CommonStepsElements.userintentionallyfailedtestcase(CommonStepsElements.java:72)
at âœ½.user intentionally failed test case(file:///C:/WorkspaceSeleniumUI/selniumUIProject/src/test/resources/features/Elements.feature:19)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="1.592"/>
</testsuite> <!-- Test -->
